version: '3.9'

services: 
  java_app: 
    container_name: java_app
    image: portiz-java-app:1.0.0
    build: .
    ports:
      - 9898:9898
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/db_nttdata
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_nttdata